export * from './ConclusionsAndFutureWork'
export * from './Content'
export * from './IntroductionAndObjectives'
export * from './Presentation'
export * from './PreviousKnowledge'
export * from './References'
export * from './Results'
export * from './StructureAndMethod'
